#!/usr/bin/env python3
"""
scripts/lean_inventory.py

Scans every .lean file under lean/ and proof/, extracts every
theorem/lemma/def/inductive/structure declaration with its file and line number,
counts lines (wc -l equivalent), and generates docs/LEAN_INVENTORY.md.
"""

import os
import re
import sys

DECL_PATTERN = re.compile(r'^\s*(theorem|lemma|def|inductive|structure)\s+([A-Za-z0-9_\'\.]+)')

def get_lean_files(root):
    lean_files = []
    for base in ['lean', 'proof']:
        base_dir = os.path.join(root, base)
        if not os.path.isdir(base_dir):
            continue
        for dirpath, _, filenames in os.walk(base_dir):
            if '.lake' in dirpath:
                continue
            for f in sorted(filenames):
                if f.endswith('.lean'):
                    full = os.path.join(dirpath, f)
                    rel = os.path.relpath(full, root).replace('\\', '/')
                    lean_files.append((rel, full))
    return sorted(lean_files, key=lambda x: x[0])

def scan_file(full_path, rel_path):
    with open(full_path, 'r', encoding='utf-8') as fh:
        lines = fh.readlines()
    total_lines = len(lines)
    decls = []
    for idx, line in enumerate(lines, 1):
        m = DECL_PATTERN.match(line)
        if m:
            kind = m.group(1)
            name = m.group(2)
            decls.append({
                'kind': kind,
                'name': name,
                'line': idx,
            })
    return {
        'path': rel_path,
        'lines': total_lines,
        'decls': decls,
    }

def build_inventory(root):
    files = get_lean_files(root)
    inventory = []
    for rel_path, full_path in files:
        inventory.append(scan_file(full_path, rel_path))
    return inventory

def generate_markdown(inventory):
    out = []
    out.append("<!-- AUTO-GENERATED BY scripts/lean_inventory.py - DO NOT EDIT -->")
    out.append("# Lean 4 Mechanized Proof Inventory\n")
    out.append("This inventory is strictly generated from the active repository sources under `lean/` and `proof/`.")
    out.append("All file paths, line counts, and theorem declarations are mechanically validated.\n")

    # Summary table
    out.append("## File Summary\n")
    out.append("| File Path | Lines (`wc -l`) | Theorems/Lemmas | Defs/Types | Total Declarations |")
    out.append("|:---|:---:|:---:|:---:|:---:|")

    total_all_lines = 0
    total_all_thms = 0
    total_all_defs = 0

    for item in inventory:
        path = item['path']
        lines = item['lines']
        thms = sum(1 for d in item['decls'] if d['kind'] in ('theorem', 'lemma'))
        defs = sum(1 for d in item['decls'] if d['kind'] in ('def', 'inductive', 'structure'))
        total_decls = len(item['decls'])
        total_all_lines += lines
        total_all_thms += thms
        total_all_defs += defs
        out.append(f"| [`{path}`](../{path}) | {lines} | {thms} | {defs} | {total_decls} |")

    out.append(f"| **Total** | **{total_all_lines}** | **{total_all_thms}** | **{total_all_defs}** | **{total_all_thms + total_all_defs}** |\n")

    # Detailed listing per file
    out.append("## Declarations by File\n")
    for item in inventory:
        path = item['path']
        lines = item['lines']
        decls = item['decls']
        out.append(f"### [`{path}`](../{path}) ({lines} lines)\n")
        if not decls:
            out.append("_No exported top-level declarations (wrapper, imports, or test runner)._\n")
            continue
        out.append("| Line | Kind | Declaration Identifier |")
        out.append("|:---:|:---|:---|")
        for d in decls:
            out.append(f"| {d['line']} | `{d['kind']}` | `{d['name']}` |")
        out.append("")

    return "\n".join(out) + "\n"

def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    inv = build_inventory(root)
    md = generate_markdown(inv)
    out_path = os.path.join(root, "docs", "LEAN_INVENTORY.md")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(md)
    print(f"Generated {out_path} ({len(inv)} Lean files scanned, {sum(item['lines'] for item in inv)} total lines).")

if __name__ == "__main__":
    main()
